<!doctype html>
<html lang="pt-BR">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Formulário 3</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"></head>
<body><div class="container py-3"><h1 class="text-center mb-4">Cadastro de Parceiro</h1><form method="post">
<div class="row mb-3"><div class="col-md-6"><label for="nome_parceiro" class="form-label">Nome do Parceiro</label><input type="text" id="nome_parceiro" name="nome_parceiro" class="form-control"></div><div class="col-md-6"><label for="email_parceiro" class="form-label">E-mail do Parceiro</label><input type="email" id="email_parceiro" name="email_parceiro" class="form-control"></div></div>
<div class="row mb-3"><div class="col-md-6"><label for="razao_social" class="form-label">Razão Social</label><input type="text" id="razao_social" name="razao_social" class="form-control"></div><div class="col-md-6"><label for="celular" class="form-label">Celular</label><input type="text" id="celular" name="celular" class="form-control"></div></div>
<div class="mb-3"><label for="endereco" class="form-label">Endereço</label><textarea id="endereco" name="endereco" class="form-control" rows="3"></textarea></div>
<div class="row mb-3"><div class="col-md-6"><label for="data_inicio" class="form-label">Data de Início do Contrato</label><input type="text" id="data_inicio" name="data_inicio" class="form-control" placeholder="Data de início"></div><div class="col-md-6"><label for="data_termino" class="form-label">Data de Término do Contrato</label><input type="text" id="data_termino" name="data_termino" class="form-control" placeholder="Data de término"></div></div>
<div class="row mb-3"><div class="col-md-6"><label for="valor_minimo" class="form-label">Valor Mínimo do Empréstimo</label><input type="text" id="valor_minimo" name="valor_minimo" class="form-control"></div><div class="col-md-6"><label for="valor_maximo" class="form-label">Valor Máximo do Empréstimo</label><input type="text" id="valor_maximo" name="valor_maximo" class="form-control"></div></div>
<div class="row mb-3"><div class="col-md-6"><label for="taxa_juros" class="form-label">Taxa de Juros</label><input type="text" id="taxa_juros" name="taxa_juros" class="form-control"></div><div class="col-md-6"><label for="valor_deposito" class="form-label">Valor do Depósito</label><input type="text" id="valor_deposito" name="valor_deposito" class="form-control"></div></div>
<button type="submit" class="btn btn-primary">Salvar</button></form></div></body></html>
